[theme]
builtin = "Noctalia"
community_palette = "Doomed"
mode = "dark"
source = "builtin"
wallpaper_scheme = "m3-tonal-spot"

[theme.templates]
builtin_ids = ["btop", "gtk3", "gtk4", "niri", "qt"]
community_ids = ["zen-browser", "telegram", "vscode"]
